### ISSUE TITLE
Get pinged for any PR that touches files you care about

### ISSUE THREAD

**Issue by nchammas** [databricks/spark-pr-dashboard#47]
This is a direct ripoff of Phabricator's Herald, but it might be very useful if we had some rudimentary PR notification system.

Basically: If a PR touches any file that contains this string in its name, ping these people.

**Comment by shivaram** [comment]
Instead of a file-level granularity it might even be enough to have be per-component. So users can subscribe to Python, EC2 or something like that

**Comment by nchammas** [comment]
That sounds good to me.

**Comment by JoshRosen** [comment]
Instead of having Spark PRs be responsible for sending messages, what if we provided per-component RSS feeds?  There's already a nice ecosystem of tools for transforming RSS feeds into your notification of choice (emails, irc messages, tweets, etc).  This could probably be hacked together in an hour or so, tops.

**Comment by nchammas** [comment]
Something like this can be done with GitHub teams and [CODEOWNERS][co]. It's not as flexible as a system for arbitrary PR activity subscriptions, but perhaps it's good enough.

[co]: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
